test1

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -1,6 +1,4 @@
 name: Push to Docker Hub
-
-# Run when you push to main
 on:
   push:
     branches: [main]
@@ -8,12 +6,9 @@ on:
 jobs:
   docker:
     runs-on: ubuntu-latest
-
     steps:
-      # 1) Get code
       - uses: actions/checkout@v4
 
-      # 2) Install Java 17
       - uses: actions/setup-java@v4
         with:
           java-version: "17"
@@ -29,25 +24,23 @@ jobs:
       # 4) Build jar
       - run: ./gradlew bootJar -x test --no-daemon
 
-      # 5) Check secret exists (add DOCKERHUB_TOKEN in GitHub repo Settings → Secrets)
-      - name: Check Docker Hub token
-        env:
-          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-        run: |
-          if [ -z "$DOCKERHUB_TOKEN" ]; then
-            echo "ERROR: Secret DOCKERHUB_TOKEN is missing."
-            echo "Add it: GitHub repo → Settings → Secrets and variables → Actions"
-            echo "Get token: https://hub.docker.com/settings/security"
-            exit 1
-          fi
-
-      # 6) Login: docker login -u kansokmean
-      - name: Login Docker Hub
-        env:
-          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-        run: echo "$DOCKERHUB_TOKEN" | docker login -u kansokmean --password-stdin
-
-      # 7) Build and push: kansokmean/docker:latest
-      - run: |
-          docker build -t kansokmean/docker:2.0 .
-          docker push kansokmean/docker:2.0
+#      - name: Check Docker Hub token
+#        env:
+#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+#        run: |
+#          if [ -z "$DOCKERHUB_TOKEN" ]; then
+#            echo "ERROR: Secret DOCKERHUB_TOKEN is missing."
+#            echo "Add it: GitHub repo → Settings → Secrets and variables → Actions"
+#            echo "Get token: https://hub.docker.com/settings/security"
+#            exit 1
+#          fi
+#
+#      - name: Login Docker Hub
+#        env:
+#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+#        run: echo "$DOCKERHUB_TOKEN" | docker login -u kansokmean --password-stdin
+#
+#      # 7) Build and push: kansokmean/docker:latest
+#      - run: |
+#          docker build -t kansokmean/docker:2.0 .
+#          docker push kansokmean/docker:2.0
