update2.1

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -24,23 +24,39 @@ jobs:
       # 4) Build jar
       - run: ./gradlew bootJar -x test --no-daemon
 
-#      - name: Check Docker Hub token
-#        env:
-#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-#        run: |
-#          if [ -z "$DOCKERHUB_TOKEN" ]; then
-#            echo "ERROR: Secret DOCKERHUB_TOKEN is missing."
-#            echo "Add it: GitHub repo → Settings → Secrets and variables → Actions"
-#            echo "Get token: https://hub.docker.com/settings/security"
-#            exit 1
-#          fi
-#
+      - name: Check Docker Hub token
+        env:
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+        run: |
+          if [ -z "$DOCKERHUB_TOKEN" ]; then
+            echo "ERROR: Secret DOCKERHUB_TOKEN is missing."
+            echo "Add it: GitHub repo → Settings → Secrets and variables → Actions"
+            echo "Get token: https://hub.docker.com/settings/security"
+            exit 1
+          fi
+
+      - name: Login Docker Hub
+        env:
+          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+        run: echo "$DOCKERHUB_TOKEN" | docker login -u kansokmean --password-stdin
+
 #      - name: Login Docker Hub
-#        env:
-#          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-#        run: echo "$DOCKERHUB_TOKEN" | docker login -u kansokmean --password-stdin
-#
-#      # 7) Build and push: kansokmean/docker:latest
+#        uses: docker/login-action@v3
+#        with:
+#          username: ${{ secrets.DOCKER_USERNAME }}
+#          password: ${{ secrets.DOCKER_PASSWORD }}
+
+
+      # 7) Build and push: kansokmean/docker:latest
 #      - run: |
 #          docker build -t kansokmean/docker:2.0 .
 #          docker push kansokmean/docker:2.0
+
+      - name: Build and push image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: |
+            ${{ secrets.DOCKER_USERNAME }}/spring-docker:latest
+            ${{ secrets.DOCKER_USERNAME }}/spring-docker:${{ github.sha }}
